import type { OscarCategory } from '../types'

export const OSCAR_CATEGORIES: OscarCategory[] = [
  { id: 'picture', name: 'Best Picture', shortName: 'Picture', group: 'Top awards' },
  {
    id: 'director',
    name: 'Best Director',
    shortName: 'Director',
    group: 'Top awards',
    detailLabel: 'Director',
    detailPlaceholder: 'Director name',
  },
  {
    id: 'actor-leading',
    name: 'Actor in a Leading Role',
    shortName: 'Leading Actor',
    group: 'Performances',
    detailLabel: 'Performer',
    detailPlaceholder: 'Actor name',
  },
  {
    id: 'actress-leading',
    name: 'Actress in a Leading Role',
    shortName: 'Leading Actress',
    group: 'Performances',
    detailLabel: 'Performer',
    detailPlaceholder: 'Actress name',
  },
  {
    id: 'actor-supporting',
    name: 'Actor in a Supporting Role',
    shortName: 'Supporting Actor',
    group: 'Performances',
    detailLabel: 'Performer',
    detailPlaceholder: 'Actor name',
  },
  {
    id: 'actress-supporting',
    name: 'Actress in a Supporting Role',
    shortName: 'Supporting Actress',
    group: 'Performances',
    detailLabel: 'Performer',
    detailPlaceholder: 'Actress name',
  },
  {
    id: 'original-screenplay',
    name: 'Best Original Screenplay',
    shortName: 'Original Screenplay',
    group: 'Writing',
    detailLabel: 'Writer',
    detailPlaceholder: 'Writer name',
  },
  {
    id: 'adapted-screenplay',
    name: 'Best Adapted Screenplay',
    shortName: 'Adapted Screenplay',
    group: 'Writing',
    detailLabel: 'Writer',
    detailPlaceholder: 'Writer name',
  },
  {
    id: 'cinematography',
    name: 'Best Cinematography',
    shortName: 'Cinematography',
    group: 'Craft',
    detailLabel: 'Cinematographer',
    detailPlaceholder: 'Cinematographer name (optional)',
  },
  {
    id: 'costume-design',
    name: 'Best Costume Design',
    shortName: 'Costume Design',
    group: 'Craft',
    detailLabel: 'Designer',
    detailPlaceholder: 'Costume designer (optional)',
  },
  {
    id: 'film-editing',
    name: 'Best Film Editing',
    shortName: 'Film Editing',
    group: 'Craft',
    detailLabel: 'Editor',
    detailPlaceholder: 'Editor name (optional)',
  },
  {
    id: 'makeup-hairstyling',
    name: 'Best Makeup and Hairstyling',
    shortName: 'Makeup & Hairstyling',
    group: 'Craft',
    detailLabel: 'Artist or team',
    detailPlaceholder: 'Artist or team (optional)',
  },
  {
    id: 'production-design',
    name: 'Best Production Design',
    shortName: 'Production Design',
    group: 'Craft',
    detailLabel: 'Designer',
    detailPlaceholder: 'Production designer (optional)',
  },
  {
    id: 'sound',
    name: 'Best Sound',
    shortName: 'Sound',
    group: 'Craft',
    detailLabel: 'Sound team',
    detailPlaceholder: 'Sound team (optional)',
  },
  {
    id: 'visual-effects',
    name: 'Best Visual Effects',
    shortName: 'Visual Effects',
    group: 'Craft',
    detailLabel: 'VFX team',
    detailPlaceholder: 'VFX team (optional)',
  },
  {
    id: 'original-score',
    name: 'Best Original Score',
    shortName: 'Original Score',
    group: 'Craft',
    detailLabel: 'Composer',
    detailPlaceholder: 'Composer name (optional)',
  },
  {
    id: 'original-song',
    name: 'Best Original Song',
    shortName: 'Original Song',
    group: 'Craft',
    detailLabel: 'Song',
    detailPlaceholder: 'Song title',
  },
  {
    id: 'casting',
    name: 'Best Casting',
    shortName: 'Casting',
    group: 'Craft',
    detailLabel: 'Casting director',
    detailPlaceholder: 'Casting director (optional)',
  },
  {
    id: 'animated-feature',
    name: 'Best Animated Feature Film',
    shortName: 'Animated Feature',
    group: 'Features',
  },
  {
    id: 'international-feature',
    name: 'Best International Feature Film',
    shortName: 'International Feature',
    group: 'Features',
  },
  {
    id: 'documentary-feature',
    name: 'Best Documentary Feature Film',
    shortName: 'Documentary Feature',
    group: 'Features',
  },
  {
    id: 'animated-short',
    name: 'Best Animated Short Film',
    shortName: 'Animated Short',
    group: 'Short films',
  },
  {
    id: 'documentary-short',
    name: 'Best Documentary Short Film',
    shortName: 'Documentary Short',
    group: 'Short films',
  },
  {
    id: 'live-action-short',
    name: 'Best Live Action Short Film',
    shortName: 'Live Action Short',
    group: 'Short films',
  },
]

export const CATEGORY_GROUPS = [
  'Top awards',
  'Performances',
  'Writing',
  'Craft',
  'Features',
  'Short films',
] as const